[package]
name = "os"
version = "1.0.0"
edition = "2024"
description = "A text adventure inspired miniature operating system for embedded RISC V RV32I."
keywords = ["text adventure", "operating system"]
license = "Unlicense"
repository = "https://github.com/calint/rust_rv32i_os"
categories = ["embedded", "no-std", "operating-systems", "text-adventures"]

[[bin]]
name = "firmware"
path = "src/main.rs"
test = false         # disable testing
bench = false        # ...

[profile.release]
opt-level = "z"   # optimize for size
debug = true      # include debugging symbols to generate better 'firmware.lst'
lto = true        # enable link time optimization
codegen-units = 1 # parallel code generation units, 1 for slightly better optimizations
panic = "abort"   # abort immediately rather than unwind

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "warn"
unwrap_used = "warn"
todo = "warn"
unreachable = "warn"
alloc_instead_of_core = "warn"
